HT_21/cart/urls.py
from django.urls import path

from .views import cart_view
from .views import increase_item_in_cart_quantity
from .views import decrease_item_in_cart_quantity
from .views import remove_item_in_cart
from .views import clear_item_in_cart
from .views import submit_order

app_name = "cart"
urlpatterns = [
    path("", cart_view, name="products_in_cart_list"),
    path("quantity/increase/<int:pk>/", increase_item_in_cart_quantity, name="increase_item_in_cart_quantity"),
    path("quantity/decrease/<int:pk>/", decrease_item_in_cart_quantity, name="decrease_item_in_cart_quantity"),
    path("remove/<int:pk>/", remove_item_in_cart, name="remove_item_in_cart"),
    path("clear/", clear_item_in_cart, name="clear_item_in_cart"),
    path("submit/", submit_order, name="submit_order"),
]

HT_21/cart/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.urls import reverse

from products.models import Product


@login_required
def increase_item_in_cart_quantity(request, pk):
    product_id = str(pk)
    cart = request.session.get('cart') or {}
    if product_id in cart:
        cart[product_id] += 1
    else:
        cart[product_id] = 1
    request.session['cart'] = cart
    return redirect(request.META.get('HTTP_REFERER', reverse('products:products_list')))


@login_required
def decrease_item_in_cart_quantity(request, pk):
    product_id = str(pk)
    cart = request.session.get('cart') or {}
    if product_id in cart:
        is_cart = str(request.META.get('HTTP_REFERER', 'not_cart'))[-5:] == 'cart/'
        if not is_cart and cart[product_id] == 1:
            cart.pop(product_id)
        elif cart[product_id] > 0:
            cart[product_id] -= 1
    request.session['cart'] = cart
    return redirect(request.META.get('HTTP_REFERER', reverse('products:products_list')))


@login_required
def remove_item_in_cart(request, pk):
    product_id = str(pk)
    if product_id:
        cart = request.session.get('cart') or {}
        cart.pop(product_id)
        request.session['cart'] = cart
    return redirect(request.META.get('HTTP_REFERER', reverse('products:products_list')))


@login_required
def clear_item_in_cart(request):
    cart = request.session.get('cart') or {}
    cart.clear()
    request.session['cart'] = cart
    return redirect(request.META.get('HTTP_REFERER', reverse('products:products_list')))


@login_required
def submit_order(request):
    cart = request.session.get('cart') or {}
    cart.clear()
    request.session['cart'] = cart
    messages.success(request, 'Замовлення прийнято в обробку.')
    return redirect(reverse('products:products_list'))


@login_required
def cart_view(request):
    cart_items = []
    total = 0
    if request.method == 'GET':
        cart = request.session.get('cart') or {}
        for product_id, product_quantity in cart.items():
            product = get_object_or_404(Product, pk=product_id)
            cart_item_total = product.price * product_quantity
            total += cart_item_total
            cart_items.append({'product': product, 'quantity': product_quantity, 'item_total': cart_item_total})
    return render(request, 'products_in_cart_list.html',
                  {'is_empty': len(cart_items) == 0, 'cart_items': cart_items, 'total': total})

HT_21/cart/templates/products_in_cart_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Корзина</title>
    <!-- Підключення Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <style>
      table {
        border-collapse: collapse;
        width: 100%;
      }

      th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
      }

      th {
        background-color: #f2f2f2;
      }

      .btn {
        border: none; /* Видалити границі кнопки */
        background: none; /* Видалити фон кнопки, якщо він є */
        cursor: pointer; /* Зробити курсор вказівником при наведенні */
      }
    </style>
</head>
<body>

{% if request.user.is_authenticated %}
    <p style="text-align: right;">
        {% if request.user.is_superuser %}
            <i class="fas fa-crown"></i>&nbsp;&nbsp;
        {% endif %}
        Користувач: {{ request.user.username }}&nbsp;&nbsp;
        <a href="{% url 'users_accounts:logout' %}">
            <button class="btn btn-outline-secondary ml-auto" type="button">
                <i class="fas fa-sign-out-alt"></i>&nbsp;&nbsp;Вийти
            </button>
        </a>
    </p>
{% else %}
    <p style="text-align: right;">
        Гість&nbsp;&nbsp;
        <a href="{% url 'users_accounts:login' %}">
            <button class="btn btn-outline-secondary ml-auto" type="button">
                <i class="fas fa-sign-in-alt"></i>&nbsp;&nbsp;Увійти
            </button>
        </a>
    </p>
{% endif %}

<h2>Товари в корзині</h2>

{% if is_empty %}
    <br>
    Корзина пуста, перейдіть до каталогу продуктів, щоб додати товари
{% else %}
    <p style="text-align: right;">
        <a href="{% url 'cart:clear_item_in_cart' %}">
            <button class="btn btn-outline-secondary float-right" type="button">
                <h2><i class="fas fa-times"></i> Очистити всю корзину</h2>
            </button>
        </a>
    </p>

    <table>
    <thead>
        <tr>
            <th>Назва</th>
            <th style="text-align: center; width: 80px;">Ціна</th>
            <th style="text-align: center; width: 80px;">Кількість</th>
            <th style="text-align: center; width: 80px;">Вартість</th>
            <th style="text-align: center; width: 80px;">Видалити</th>
        </tr>
    </thead>
    <tbody>
        {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="{% url 'products:product_details' pk=cart_item.product.pk %}">
                        {{ cart_item.product.name }}
                    </a>
                </td>
                <td style="text-align: center;">{{ cart_item.product.price }}</td>
                <td style="text-align: center;">
                    <a href="{% url 'cart:decrease_item_in_cart_quantity' pk=cart_item.product.pk %}">
                        <button class="btn btn-outline-secondary" type="button"><i class="fas fa-minus"></i></button>
                    </a>
                    {{ cart_item.quantity }}
                    <a href="{% url 'cart:increase_item_in_cart_quantity' pk=cart_item.product.pk %}">
                        <button class="btn btn-outline-secondary" type="button"><i class="fas fa-plus"></i></button>
                    </a>
                </td>
                <td style="text-align: center;">{{ cart_item.item_total }}</td>
                <td style="text-align: center;">
                    <a href="{% url 'cart:remove_item_in_cart' pk=cart_item.product.pk %}">
                        <i class="fas fa-trash-alt"></i>
                    </a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <td><strong>Всього вартість замовлення</strong></td>
            <td colspan="4" style="text-align: center;"><strong>{{ total }}</strong></td>
        </tr>
    </tfoot>
    </table>

    <p style="text-align: right;">
        <a href="{% url 'cart:submit_order' %}">
            <button class="btn btn-outline-primary" type="button">
                <h2><i class="fas fa-check-circle"></i> Підтвердити замовлення</h2>
            </button>
        </a>
    </p>
{% endif %}

<br><br>
{% if request.user.is_superuser %}
    <p><a href="{% url 'products:product_input' %}">Додати продукти в каталог</a></p>
{% endif %}
<p><a href="{% url 'products:products_list' %}">Каталог продуктів</a></p>
</body>
</html>