HT_24/cart/urls.py
from django.urls import path

from .views import cart_view
from .views import ajax_change_quantity
from .views import ajax_remove_item
from .views import submit_order

app_name = "cart"
urlpatterns = [
    path("", cart_view, name="products_in_cart_list"),
    path('ajax_change_quantity/', ajax_change_quantity, name='ajax_change_quantity'),
    path('ajax_remove_item/', ajax_remove_item, name='ajax_remove_item'),
    path("submit/", submit_order, name="submit_order"),
]

HT_24/products/urls.py
from django.urls import path

from .views import product_input
from .views import ProductsListView
from .views import ProductDetailView
from .views import product_edit
from .views import product_update_from_sears_com
from .views import product_delete

app_name = "products"
urlpatterns = [
    path("products/add/", product_input, name="product_input"),
    path("", ProductsListView.as_view(), name="products_list"),
    path("products/category_filter/<slug:cat_slug>/", ProductsListView.as_view(), name='products_list_by_category'),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="product_details"),
    path("products/edit/<int:pk>/", product_edit, name="product_edit"),
    path("products/update/<int:pk>/", product_update_from_sears_com, name="product_update_from_sears_com"),
    path("products/delete/<int:pk>/", product_delete, name="product_delete"),
]

HT_24/task_01/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

api = [
    path("", include("products.api_urls")),
    path("", include("cart.api_urls")),
]

urlpatterns = [
    path("", include("products.urls")),
    path("cart/", include("cart.urls")),
    path("users_accounts/", include("users_accounts.urls")),
    path("api/", include(api)),
    path('admin/', admin.site.urls),
]

HT_24/users_accounts/urls.py
from django.urls import path

from .views import user_login
from .views import logout

app_name = "users_accounts"
urlpatterns = [
    path("login/", user_login, name="login"),
    path("logout/", logout, name="logout"),
]

HT_24/products/models.py
from django.db import models


class Product(models.Model):
    product_id = models.CharField(max_length=50, unique=True, verbose_name='ID')
    name = models.CharField(max_length=255, verbose_name='Назва')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Ціна')
    short_description = models.TextField(blank=True, null=True, verbose_name='Короткий опис')
    brand = models.CharField(max_length=100, blank=True, null=True, verbose_name='Бренд')
    category = models.ForeignKey(
        'Category',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='products',
        verbose_name='Категорія')
    link_to_product = models.URLField(max_length=255, verbose_name='Лінк на продукт')
    update_date = models.DateTimeField(verbose_name='Дата оновлення даних')

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=150, verbose_name='Назва категорії')

    def __str__(self):
        return self.name

HT_24/products/forms.py
from django import forms
from django.core.validators import RegexValidator

from .models import Product


class GetProductIdsForm(forms.Form):
    ids_raw_data = forms.CharField(
        label='Введіть ID продуктів, розділені комою',
        max_length=500000,
        validators=[
            RegexValidator(
                regex=r'^[a-zA-Z\d,]+$',
                code='invalid_input',
            ),
        ]
    )


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['product_id', 'name', 'price', 'short_description', 'brand', 'category', 'link_to_product',
                  'update_date']

HT_24/products/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.generic import ListView
from django.views.generic import DetailView
from .tasks import run_scraping_task

from .forms import GetProductIdsForm, ProductForm
from .models import Product, Category


def product_input(request):
    if request.user and not request.user.is_superuser:
        messages.error(request, 'Доступ до сторінки додавання нових продуктів мають лише суперюзери.')
        return redirect(reverse('products:products_list'))

    if request.method == 'POST':
        form = GetProductIdsForm(request.POST)
        if form.is_valid():
            ids = form.cleaned_data['ids_raw_data']
            run_scraping_task.delay(ids=ids)
            messages.success(request, 'Дані успішно додані в чергу на обробку!')
        else:
            messages.error(request, 'Дозволені тільки латинські букви, цифри та кома!')

    form = GetProductIdsForm()
    return render(request, 'product_input.html', {'form': form})


class ProductsListView(ListView):
    model = Product
    template_name = "products_list.html"
    context_object_name = "products_list"
    paginate_by = 10
    ordering = ['-update_date']

    def get_queryset(self):
        queryset = super().get_queryset()
        category_slug = self.kwargs.get('cat_slug')
        if category_slug:
            queryset = queryset.filter(category_id=category_slug)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart = self.request.session.get('cart') or {}
        items = []
        for product in context['object_list']:
            product_id = str(product.pk)
            quantity = cart[product_id] if product_id in cart.keys() else 0
            items.append({'product': product, 'quantity': quantity})
        context['items_list'] = items
        context['categories'] = Category.objects.all()
        context['filtered_category'] = self.get_filtered_category()
        return context

    def get_filtered_category(self):
        filtered_category = Category.objects.filter(id=self.kwargs.get('cat_slug')).first()
        if filtered_category:
            filtered_category_label = filtered_category.name
        else:
            filtered_category_label = 'Всі категорії'
        return filtered_category_label


class ProductDetailView(DetailView):
    model = Product
    template_name = "product_details.html"
    context_object_name = "product_details"


def product_edit(request, pk):
    if request.user and not request.user.is_superuser:
        messages.error(request, 'Доступ до сторінки редагування продуктів мають лише суперюзери.')
        return redirect(reverse('products:products_list'))

    edit_object = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        form = ProductForm(request.POST, instance=edit_object)
        if form.is_valid():
            form.save()
            messages.success(request, f'Дані продукта ID={pk} були успішно збережені.')
            return redirect(reverse('products:products_list'))
        else:
            messages.error(request, f'Введено невалідні дані. Повторіть спробу!')

    form = ProductForm(instance=edit_object)
    return render(request, 'product_edit.html', {'form': form, 'pk': pk})


def product_update_from_sears_com(request, pk):
    if request.user and not request.user.is_superuser:
        messages.error(request, 'Доступ до сторінки оновлення продуктів мають лише суперюзери.')
        return redirect(reverse('products:products_list'))

    edit_object = get_object_or_404(Product, pk=pk)
    handle_valid_data({'ids_raw_data': edit_object.product_id})
    messages.success(request, 'Дані успішно додані в чергу на оновлення!')
    return redirect(reverse('products:products_list'))


def product_delete(request, pk):
    if request.user and not request.user.is_superuser:
        messages.error(request, 'Доступ до сторінки видалення продуктів мають лише суперюзери.')
        return redirect(reverse('products:products_list'))

    delete_object = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        if request.POST.get('confirm_delete'):
            delete_object.delete()
            messages.success(request, f'Продукт ID={pk} був успішно видалений.')
            return redirect(reverse('products:products_list'))

    referer_url = request.META.get('HTTP_REFERER', reverse('products:products_list'))
    return render(request, 'product_delete.html',
                  {'delete_object': delete_object, 'referer_url': referer_url})

HT_24/products/templates/product_delete.html
<!DOCTYPE html>
<html>
<head>
    <title>Видалення</title>
    <!-- Підключення Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <style>
      table {
        border-collapse: collapse;
        width: 100%;
      }

      th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
      }

      th {
        background-color: #f2f2f2;
      }

      .btn {
        border: none; /* Видалити границі кнопки */
        background: none; /* Видалити фон кнопки, якщо він є */
        cursor: pointer; /* Зробити курсор вказівником при наведенні */
      }
    </style>
    <script>
        // Функція для ховання повідомлення через певний час
        function hideMessage() {
            var message = document.getElementById('message');
            message.style.display = 'none';
        }

        // Викликаємо функцію при завантаженні сторінки
        window.onload = function() {
            var message = document.getElementById('message');
            if (message) {
                setTimeout(hideMessage, 1500);  // Ховаємо повідомлення через 1,5 секунди (1500 мілісекунд)
            }
        };
    </script>
</head>
<body>

{% if request.user.is_authenticated %}
    <p style="text-align: right;">
        {% if request.user.is_superuser %}
            <i class="fas fa-crown"></i>&nbsp;&nbsp;
        {% endif %}
        Користувач: {{ request.user.username }}&nbsp;&nbsp;
        <a href="{% url 'users_accounts:logout' %}">
            <button class="btn btn-outline-secondary ml-auto" type="button">
                <i class="fas fa-sign-out-alt"></i>&nbsp;&nbsp;Вийти
            </button>
        </a>
    </p>
{% else %}
    <p style="text-align: right;">
        Гість&nbsp;&nbsp;
        <a href="{% url 'users_accounts:login' %}">
            <button class="btn btn-outline-secondary ml-auto" type="button">
                <i class="fas fa-sign-in-alt"></i>&nbsp;&nbsp;Увійти
            </button>
        </a>
    </p>
{% endif %}

<h2>Видалення продукта ID={{ delete_object.pk }}</h2>
<p>Ви впевнені, що хочете видалити продукт '{{ delete_object.name }}'?</p>
    <form method="post" action="{% url 'products:product_delete' delete_object.pk %}">
        {% csrf_token %}
        <input type="submit" name="confirm_delete" value="Так, підтверджую видалення">
    </form>
<br>
<a href="{{ referer_url }}">
    <button>Ні, повернутися до каталогу</button>
</a>

<br><br>
{% if request.user.is_superuser %}
    <p><a href="{% url 'products:product_input' %}">Додати продукти в каталог</a></p>
{% endif %}
<p><a href="{% url 'products:products_list' %}">Каталог продуктів</a></p>
{% if request.user.is_authenticated %}
    <p><a href="{% url 'cart:products_in_cart_list' %}">Перейти в корзину</a></p>
{% endif %}

{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'error' %}
            <div id="message" style="background-color: orangered;">
                <p><h1><strong>{{ message }}</strong></h1></p>
            </div>
        {% elif message.tags == 'success' %}
            <div id="message" style="background-color: limegreen;">
                <p><h1><strong>{{ message }}</strong></h1></p>
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

</body>
</html>

HT_24/products/templates/product_details.html
<!DOCTYPE html>
<html>
<head>
    <title>Продукт</title>
    <!-- Підключення Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <style>
      table {
        border-collapse: collapse;
        width: 100%;
      }

      th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
      }

      th {
        background-color: #f2f2f2;
      }

      .btn {
        border: none; /* Видалити границі кнопки */
        background: none; /* Видалити фон кнопки, якщо він є */
        cursor: pointer; /* Зробити курсор вказівником при наведенні */
      }
    </style>
</head>
<body>

{% if request.user.is_authenticated %}
    <p style="text-align: right;">
        {% if request.user.is_superuser %}
            <i class="fas fa-crown"></i>&nbsp;&nbsp;
        {% endif %}
        Користувач: {{ request.user.username }}&nbsp;&nbsp;
        <a href="{% url 'users_accounts:logout' %}">
            <button class="btn btn-outline-secondary ml-auto" type="button">
                <i class="fas fa-sign-out-alt"></i>&nbsp;&nbsp;Вийти
            </button>
        </a>
    </p>
{% else %}
    <p style="text-align: right;">
        Гість&nbsp;&nbsp;
        <a href="{% url 'users_accounts:login' %}">
            <button class="btn btn-outline-secondary ml-auto" type="button">
                <i class="fas fa-sign-in-alt"></i>&nbsp;&nbsp;Увійти
            </button>
        </a>
    </p>
{% endif %}

<h2>{{ product_details.name }}</h2>
<p><strong>Ціна:</strong> {{ product_details.price }}</p>
<p><strong>Короткий опис:</strong> {{ product_details.short_description }}</p>
<p><strong>Бренд:</strong> {{ product_details.brand }}</p>
<p><strong>Категорія:</strong> {{ product_details.category }}</p>
<p><strong>Лінк на продукт:</strong> <a href="{{ product_details.link_to_product }}">{{ product_details.link_to_product }}</a></p>
<p><strong>Дата оновлення:</strong> {{ product_details.update_date|date:"d.m.Y H:i" }}</p>

<br><br>
{% if request.user.is_superuser %}
    <p><a href="{% url 'products:product_input' %}">Додати продукти в каталог</a></p>
{% endif %}
<p><a href="{% url 'products:products_list' %}">Каталог продуктів</a></p>
{% if request.user.is_authenticated %}
    <p><a href="{% url 'cart:products_in_cart_list' %}">Перейти в корзину</a></p>
{% endif %}

</body>
</html>

HT_24/products/templates/product_edit.html
<!DOCTYPE html>
<html>
<head>
    <title>Редагування</title>
    <!-- Підключення Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <style>
      table {
        border-collapse: collapse;
        width: 100%;
      }

      th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
      }

      th {
        background-color: #f2f2f2;
      }

      .btn {
        border: none; /* Видалити границі кнопки */
        background: none; /* Видалити фон кнопки, якщо він є */
        cursor: pointer; /* Зробити курсор вказівником при наведенні */
      }
    </style>
    <script>
        // Функція для ховання повідомлення через певний час
        function hideMessage() {
            var message = document.getElementById('message');
            message.style.display = 'none';
        }

        // Викликаємо функцію при завантаженні сторінки
        window.onload = function() {
            var message = document.getElementById('message');
            if (message) {
                setTimeout(hideMessage, 1500);  // Ховаємо повідомлення через 1,5 секунди (1500 мілісекунд)
            }
        };
    </script>
</head>
<body>

{% if request.user.is_authenticated %}
    <p style="text-align: right;">
        {% if request.user.is_superuser %}
            <i class="fas fa-crown"></i>&nbsp;&nbsp;
        {% endif %}
        Користувач: {{ request.user.username }}&nbsp;&nbsp;
        <a href="{% url 'users_accounts:logout' %}">
            <button class="btn btn-outline-secondary ml-auto" type="button">
                <i class="fas fa-sign-out-alt"></i>&nbsp;&nbsp;Вийти
            </button>
        </a>
    </p>
{% else %}
    <p style="text-align: right;">
        Гість&nbsp;&nbsp;
        <a href="{% url 'users_accounts:login' %}">
            <button class="btn btn-outline-secondary ml-auto" type="button">
                <i class="fas fa-sign-in-alt"></i>&nbsp;&nbsp;Увійти
            </button>
        </a>
    </p>
{% endif %}

<h2>Редагувати продукт</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зберегти зміни</button>
</form>

<br>
<a href="{% url 'products:product_update_from_sears_com' pk=pk %}">
    <button>Оновити з магазину SEARS.COM</button>
</a>

<br><br>
{% if request.user.is_superuser %}
    <p><a href="{% url 'products:product_input' %}">Додати продукти в каталог</a></p>
{% endif %}
<p><a href="{% url 'products:products_list' %}">Каталог продуктів</a></p>
{% if request.user.is_authenticated %}
    <p><a href="{% url 'cart:products_in_cart_list' %}">Перейти в корзину</a></p>
{% endif %}

{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'error' %}
            <div id="message" style="background-color: orangered;">
                <p><h1><strong>{{ message }}</strong></h1></p>
            </div>
        {% elif message.tags == 'success' %}
            <div id="message" style="background-color: limegreen;">
                <p><h1><strong>{{ message }}</strong></h1></p>
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

</body>
</html>

HT_24/products/templates/product_input.html
<!DOCTYPE html>
<html>
<head>
    <title>Додати продукти</title>
    <!-- Підключення Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        .btn {
            border: none; /* Видалити границі кнопки */
            background: none; /* Видалити фон кнопки, якщо він є */
            cursor: pointer; /* Зробити курсор вказівником при наведенні */
        }

        form {
            display: flex;
            align-items: center;
        }

        .form-field {
            margin-right: 10px;
        }
    </style>
    <script>
        // Функція для ховання повідомлення через певний час
        function hideMessage() {
            var message = document.getElementById('message');
            message.style.display = 'none';
        }

        // Викликаємо функцію при завантаженні сторінки
        window.onload = function() {
            var message = document.getElementById('message');
            if (message) {
                setTimeout(hideMessage, 1500);  // Ховаємо повідомлення через 1,5 секунди (1500 мілісекунд)
            }
        };
    </script>
</head>
<body>

{% if request.user.is_authenticated %}
    <p style="text-align: right;">
        {% if request.user.is_superuser %}
            <i class="fas fa-crown"></i>&nbsp;&nbsp;
        {% endif %}
        Користувач: {{ request.user.username }}&nbsp;&nbsp;
        <a href="{% url 'users_accounts:logout' %}">
            <button class="btn btn-outline-secondary ml-auto" type="button">
                <i class="fas fa-sign-out-alt"></i>&nbsp;&nbsp;Вийти
            </button>
        </a>
    </p>
{% else %}
    <p style="text-align: right;">
        Гість&nbsp;&nbsp;
        <a href="{% url 'users_accounts:login' %}">
            <button class="btn btn-outline-secondary ml-auto" type="button">
                <i class="fas fa-sign-in-alt"></i>&nbsp;&nbsp;Увійти
            </button>
        </a>
    </p>
{% endif %}

<h2>Введіть будь-яку кількість ID продуктів яку хочете додати в базу збережених</h2>

<form method="post" action="{% url 'products:product_input' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <span class="form-field"></span>
    <button type="submit">Відправити</button>

    <span class="form-field"></span>

    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div id="message" style="background-color: orangered;">
                    <strong>{{ message }}</strong>
                </div>
            {% elif message.tags == 'success' %}
                <div id="message" style="background-color: limegreen;">
                    <strong>{{ message }}</strong>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}

</form>
<p><a href="{% url 'products:products_list' %}">Каталог продуктів</a></p>
{% if request.user.is_authenticated %}
    <p><a href="{% url 'cart:products_in_cart_list' %}">Перейти в корзину</a></p>
{% endif %}

</body>
</html>

HT_24/products/templates/products_list.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Каталог продуктів</title>
    <!-- Підключення Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <style>
      table {
        border-collapse: collapse;
        width: 100%;
      }

      th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
      }

      th {
        background-color: #f2f2f2;
      }

      .pagination {
        text-align: center;
        margin-top: 10px; /* Додайте відступ від верху, якщо потрібно */
      }

      .step-links {
        display: inline-block;
      }

      .step-links a {
        margin-right: 12px;
      }

      .current {
        margin-right: 12px;
      }

      .btn {
        border: none; /* Видалити границі кнопки */
        background: none; /* Видалити фон кнопки, якщо він є */
        cursor: pointer; /* Зробити курсор вказівником при наведенні */
      }
    </style>
    <script>
        // Функція для ховання повідомлення через певний час
        function hideMessage() {
            var message = document.getElementById('message');
            message.style.display = 'none';
        }

        // Викликаємо функцію при завантаженні сторінки
        window.onload = function() {
            var message = document.getElementById('message');
            if (message) {
                setTimeout(hideMessage, 1500);  // Ховаємо повідомлення через 1,5 секунди (1500 мілісекунд)
            }
        };
    </script>
</head>
<body>

{% if request.user.is_authenticated %}
    <p style="text-align: right;">
        {% if request.user.is_superuser %}
            <i class="fas fa-crown"></i>&nbsp;&nbsp;
        {% endif %}
        Користувач: {{ request.user.username }}&nbsp;&nbsp;
        <a href="{% url 'users_accounts:logout' %}">
            <button class="btn btn-outline-secondary ml-auto" type="button">
                <i class="fas fa-sign-out-alt"></i>&nbsp;&nbsp;Вийти
            </button>
        </a>
    </p>
{% else %}
    <p style="text-align: right;">
        Гість&nbsp;&nbsp;  
        <a href="{% url 'users_accounts:login' %}">
            <button class="btn btn-outline-secondary ml-auto" type="button">
                <i class="fas fa-sign-in-alt"></i>&nbsp;&nbsp;Увійти
            </button>
        </a>
    </p>
{% endif %}

<h2>Фільтри категорій збережених продуктів</h2>
<a href="{% url 'products:products_list' %}">
        Всі категорії
    </a>&nbsp;&nbsp;&nbsp;&nbsp;
{% for category in categories %}
    <a href="{% url 'products:products_list_by_category' cat_slug=category.pk %}">
        {{ category.name }}
    </a>&nbsp;&nbsp;&nbsp;&nbsp;
{% endfor %}

<br>
<h2>Список збережених продуктів ({{ filtered_category }})</h2>
<table>
<thead>
    <tr>
        <th>Назва</th>
            {% if request.user.is_superuser %}
                <th style="text-align: center; width: 100px;">Редагувати</th>
            {% endif %}
        <th style="text-align: center; width: 80px;">Ціна</th>
            {% if request.user.is_authenticated %}
                <th style="text-align: center; width: 150px;">Додати в корзину</th>
            {% endif %}
        <th style="text-align: center; width: 200px;">Дата оновлення даних</th>
    </tr>
</thead>
<tbody>
    {% for item in items_list %}
        <tr>
            <td><a href="{% url 'products:product_details' pk=item.product.pk %}">{{ item.product.name }}</a></td>

            {% if request.user.is_superuser %}
                <td style="text-align: center;">
                    <a href="{% url 'products:product_edit' pk=item.product.pk %}">
                        <i class="fas fa-edit"></i>
                    </a>
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="{% url 'products:product_delete' pk=item.product.pk %}">
                        <i class="fas fa-trash-alt"></i>
                    </a>
                </td>
            {% endif %}

            <td style="text-align: center;">{{ item.product.price }}</td>
            {% if request.user.is_authenticated %}
                <td style="text-align: center;">
                    <button class="btn btn-outline-secondary cart-btn" data-product-pk="{{ item.product.pk }}" type="button"
                            {% if item.quantity != 0 %}style="display: none;"{% endif %}>
                        <i class="fas fa-shopping-basket full-basket"></i>
                    </button>
                    <button class="btn btn-outline-secondary decrease-btn" data-product-pk="{{ item.product.pk }}" type="button"
                            {% if item.quantity == 0 %}style="display: none;"{% endif %}>
                        <i class="fas fa-minus"></i>
                    </button>
                    <span class="quantity" data-product-pk="{{ item.product.pk }}"
                          {% if item.quantity == 0 %}style="display: none;"{% endif %}>{{ item.quantity }}
                    </span>
                    <button class="btn btn-outline-secondary increase-btn" data-product-pk="{{ item.product.pk }}" type="button"
                            {% if item.quantity == 0 %}style="display: none;"{% endif %}>
                        <i class="fas fa-plus"></i>
                    </button>
                </td>
            {% endif %}
            <td style="text-align: center;">{{ item.product.update_date|date:"d.m.Y H:i" }}</td>
        </tr>
    {% endfor %}
</tbody>
</table>

<div class="pagination">
<span class="step-links">
    <br><br>
    {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; перша</a>
        <span style="margin-right: 12px;"></span>
        <a href="?page={{ page_obj.previous_page_number }}">&laquo; попередня</a>
        <span style="margin-right: 12px;"></span>
    {% endif %}

    <span class="current">
        Сторінка {{ page_obj.number }} з {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
        <span style="margin-right: 12px;"></span>
        <a href="?page={{ page_obj.next_page_number }}">наступна &raquo;</a>
        <span style="margin-right: 12px;"></span>
        <a href="?page={{ page_obj.paginator.num_pages }}">остання &raquo;</a>
    {% endif %}
</span>
</div>

<br><br>
{% if request.user.is_superuser %}
    <p><a href="{% url 'products:product_input' %}">Додати продукти в каталог</a></p>
{% endif %}

{% if request.user.is_authenticated %}
    <p><a href="{% url 'cart:products_in_cart_list' %}">Перейти в корзину</a></p>
{% endif %}

{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'error' %}
            <div id="message" style="background-color: orangered;">
                <p><h1><strong>{{ message }}</strong></h1></p>
            </div>
        {% elif message.tags == 'success' %}
            <div id="message" style="background-color: limegreen;">
                <p><h1><strong>{{ message }}</strong></h1></p>
            </div>
        {% endif %}
    {% endfor %}
{% endif %}


<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    var csrf_token = "{{ csrf_token }}";
</script>
<script src="{% static 'products/scripts.js' %}"></script>
</body>
</html>