HT_18/products/urls.py
from django.urls import path

from . import views

app_name = "products"
urlpatterns = [
    path("", views.product_input, name="product_input"),
    path("products", views.ProductsListView.as_view(), name="products_list"),
    path("product/<int:pk>", views.ProductDetailView.as_view(), name="product_details"),
]

HT_18/products/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic import DetailView

from .forms import GetProductIdsForm
from .models import Product
from .services import handle_valid_data


def product_input(request):
    success_message = None

    if request.method == 'POST':
        form = GetProductIdsForm(request.POST)
        if form.is_valid():
            handle_valid_data(form.cleaned_data)
            success_message = 'Дані успішно додані в чергу на обробку!'
        else:
            success_message = "Дозволені тільки латинські букви, цифри та кома!"

    form = GetProductIdsForm()
    return render(request, 'product_input.html', {'form': form, 'success_message': success_message})


class ProductsListView(ListView):
    model = Product
    template_name = "products_list.html"
    context_object_name = "products_list"
    paginate_by = 10
    ordering = ['-update_date']


class ProductDetailView(DetailView):
    model = Product
    template_name = "product_details.html"
    context_object_name = "product_details"

HT_18/products/templates/product_details.html
<!DOCTYPE html>
<html>
<head>
    <title>Продукт</title>
</head>
<body>

<h2>{{ product_details.name }}</h2>
<p><strong>Ціна:</strong> {{ product_details.price }}</p>
<p><strong>Короткий опис:</strong> {{ product_details.short_description }}</p>
<p><strong>Бренд:</strong> {{ product_details.brand }}</p>
<p><strong>Категорія:</strong> {{ product_details.category }}</p>
<p><strong>Лінк на продукт:</strong> <a href="{{ product_details.link_to_product }}">{{ product_details.link_to_product }}</a></p>
<p><strong>Дата оновлення:</strong> {{ product_details.update_date|date:"d.m.Y H:i" }}</p>

<br><br>
<p><a href="{% url 'products:product_input' %}">Додати продукти</a></p>
<p><a href="{% url 'products:products_list' %}">Мої продукти</a></p>
</body>
</html>

HT_18/products/templates/product_input.html
<!DOCTYPE html>
<html>
<head>
    <title>Додати продукти</title>
    <style>
        form {
            display: flex;
            align-items: center;
        }

        .form-field {
            margin-right: 10px;
        }

        .success-green {
            background-color: green;
            color: white;
        }

        .success-red {
            background-color: red;
            color: white;
        }
    </style>
    <script>
        // Функція для ховання повідомлення через певний час
        function hideMessage() {
            var successMessage = document.getElementById('success-message');
            successMessage.style.display = 'none';
        }

        // Викликаємо функцію при завантаженні сторінки
        window.onload = function() {
            var successMessage = document.getElementById('success-message');
            if (successMessage) {
                setTimeout(hideMessage, 1500);  // Ховаємо повідомлення через 1,5 секунди (1500 мілісекунд)
            }
        };
    </script>
</head>
<body>

<h2>Введіть будь-яку кількість ID продуктів яку хочете додати в базу збережених</h2>

<form method="post" action="{% url 'products:product_input' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <span class="form-field"></span>
    <button type="submit">Відправити</button>

    <span class="form-field"></span>
    {% if success_message %}
        <div id="success-message" class="
        {% if success_message == 'Дані успішно відправлені!' %}success-green
        {% elif success_message == 'Дозволені тільки цифри та кома!' %}success-red
        {% endif %}">
            <p><b>{{ success_message }}</b></p>
        </div>
    {% endif %}

</form>
<p><a href="{% url 'products:products_list' %}">Мої продукти</a></p>

</body>
</html>

HT_18/products/templates/products_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Мої продукти</title>
    <style>
      table {
        border-collapse: collapse;
        width: 100%;
      }

      th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
      }

      th {
        background-color: #f2f2f2;
      }

      .pagination {
        text-align: center;
        margin-top: 10px; /* Додайте відступ від верху, якщо потрібно */
      }

      .step-links {
        display: inline-block;
      }

      .step-links a {
        margin-right: 12px;
      }

      .current {
        margin-right: 12px;
      }
    </style>
</head>
<body>

<h2>Список збережених продуктів</h2>

<table>
<thead>
    <tr>
        <th>Назва</th>
        <th>Ціна</th>
        <th>Дата оновлення даних</th>
    </tr>
</thead>
<tbody>
    {% for product in products_list %}
        <tr>
            <td><a href="{% url 'products:product_details' pk=product.pk %}">{{ product.name }}</a></td>
            <td>{{ product.price }}</td>
            <td>{{ product.update_date|date:"d.m.Y H:i" }}</td>
        </tr>
    {% endfor %}
</tbody>
</table>

<div class="pagination">
<span class="step-links">
    <br><br>
    {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; перша</a>
        <span style="margin-right: 12px;"></span>
        <a href="?page={{ page_obj.previous_page_number }}">&laquo; попередня</a>
        <span style="margin-right: 12px;"></span>
    {% endif %}

    <span class="current">
        Сторінка {{ page_obj.number }} з {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
        <span style="margin-right: 12px;"></span>
        <a href="?page={{ page_obj.next_page_number }}">наступна &raquo;</a>
        <span style="margin-right: 12px;"></span>
        <a href="?page={{ page_obj.paginator.num_pages }}">остання &raquo;</a>
    {% endif %}
</span>
</div>

<br><br>
<p><a href="{% url 'products:product_input' %}">Додати продукти</a></p>

</body>
</html>